// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module VDecodeSimple(	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:98:7]
  input  [31:0] io_in,	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:99:14]
  output        io_isVec,	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:99:14]
                io_isConfig,	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:99:14]
                io_xrs1,	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:99:14]
                io_xrs2,	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:99:14]
                io_xrd	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:99:14]
);

  wire [11:0] decoderOut0_invInputs = ~(io_in[14:3]);	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:99:14, src/main/scala/chisel3/util/pla.scala:78:21]
  wire [3:0]  _decoderOut0_orMatrixOutputs_T =
    {&{io_in[0],
       io_in[1],
       io_in[2],
       decoderOut0_invInputs[0],
       decoderOut0_invInputs[1],
       decoderOut0_invInputs[3],
       decoderOut0_invInputs[9],
       decoderOut0_invInputs[10],
       decoderOut0_invInputs[11]},
     &{io_in[0],
       io_in[1],
       io_in[2],
       decoderOut0_invInputs[0],
       io_in[4],
       decoderOut0_invInputs[2],
       io_in[6]},
     &{io_in[0],
       io_in[1],
       io_in[2],
       decoderOut0_invInputs[0],
       decoderOut0_invInputs[1],
       decoderOut0_invInputs[3],
       io_in[12],
       io_in[14]},
     &{io_in[0],
       io_in[1],
       io_in[2],
       decoderOut0_invInputs[0],
       decoderOut0_invInputs[1],
       decoderOut0_invInputs[3],
       io_in[13],
       io_in[14]}};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:19]
  wire [28:0] decoderOut1_invInputs = ~(io_in[31:3]);	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:99:14, src/main/scala/chisel3/util/pla.scala:78:21]
  wire [10:0] _decoderOut1_andMatrixOutputs_T_3 =
    {io_in[0],
     io_in[1],
     io_in[2],
     decoderOut1_invInputs[0],
     io_in[4],
     decoderOut1_invInputs[2],
     io_in[6],
     io_in[12],
     io_in[13],
     io_in[14],
     decoderOut1_invInputs[28]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [16:0] _decoderOut1_andMatrixOutputs_T_5 =
    {io_in[0],
     io_in[1],
     io_in[2],
     decoderOut1_invInputs[0],
     io_in[4],
     decoderOut1_invInputs[2],
     io_in[6],
     io_in[12],
     io_in[13],
     io_in[14],
     decoderOut1_invInputs[22],
     decoderOut1_invInputs[23],
     decoderOut1_invInputs[24],
     decoderOut1_invInputs[25],
     decoderOut1_invInputs[26],
     decoderOut1_invInputs[27],
     io_in[31]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [2:0]  _decoderOut1_orMatrixOutputs_T =
    {&_decoderOut1_andMatrixOutputs_T_3,
     &_decoderOut1_andMatrixOutputs_T_5,
     &{io_in[0],
       io_in[1],
       io_in[2],
       decoderOut1_invInputs[0],
       io_in[4],
       decoderOut1_invInputs[2],
       io_in[6],
       io_in[12],
       io_in[13],
       io_in[14],
       io_in[30],
       io_in[31]}};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:19]
  wire [28:0] decoderOut2_invInputs = ~(io_in[31:3]);	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:99:14, src/main/scala/chisel3/util/pla.scala:78:21]
  assign io_isVec = |_decoderOut0_orMatrixOutputs_T;	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:98:7, src/main/scala/chisel3/util/pla.scala:114:{19,36}]
  assign io_isConfig = |_decoderOut1_orMatrixOutputs_T;	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:98:7, src/main/scala/chisel3/util/pla.scala:114:{19,36}]
  assign io_xrs1 =
    (|{&{io_in[0],
         io_in[1],
         io_in[2],
         decoderOut1_invInputs[0],
         decoderOut1_invInputs[1],
         decoderOut1_invInputs[3]},
       &{io_in[0],
         io_in[1],
         io_in[2],
         decoderOut1_invInputs[0],
         io_in[4],
         decoderOut1_invInputs[2],
         io_in[6],
         decoderOut1_invInputs[9],
         io_in[14]},
       &_decoderOut1_andMatrixOutputs_T_3,
       &_decoderOut1_andMatrixOutputs_T_5}) & (|_decoderOut0_orMatrixOutputs_T);	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:98:7, :117:29, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}]
  assign io_xrs2 =
    (|{&{io_in[0],
         io_in[1],
         io_in[2],
         decoderOut1_invInputs[0],
         decoderOut1_invInputs[1],
         decoderOut1_invInputs[3],
         decoderOut1_invInputs[23],
         io_in[27]},
       &_decoderOut1_andMatrixOutputs_T_5}) & (|_decoderOut0_orMatrixOutputs_T);	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:98:7, :118:29, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}]
  assign io_xrd =
    (|{&{io_in[0],
         io_in[1],
         io_in[2],
         decoderOut2_invInputs[0],
         io_in[4],
         decoderOut2_invInputs[2],
         io_in[6],
         decoderOut2_invInputs[9],
         io_in[13],
         decoderOut2_invInputs[11],
         decoderOut2_invInputs[13],
         decoderOut2_invInputs[14],
         decoderOut2_invInputs[15],
         io_in[19],
         decoderOut2_invInputs[23],
         decoderOut2_invInputs[24],
         decoderOut2_invInputs[25],
         decoderOut2_invInputs[26],
         io_in[30],
         decoderOut2_invInputs[28]},
       &{io_in[0],
         io_in[1],
         io_in[2],
         decoderOut2_invInputs[0],
         io_in[4],
         decoderOut2_invInputs[2],
         io_in[6],
         decoderOut2_invInputs[9],
         io_in[13],
         decoderOut2_invInputs[11],
         decoderOut2_invInputs[12],
         decoderOut2_invInputs[13],
         decoderOut2_invInputs[14],
         decoderOut2_invInputs[15],
         decoderOut2_invInputs[16],
         io_in[25],
         decoderOut2_invInputs[23],
         decoderOut2_invInputs[24],
         decoderOut2_invInputs[25],
         decoderOut2_invInputs[26],
         io_in[30],
         decoderOut2_invInputs[28]}}) | (|_decoderOut1_orMatrixOutputs_T);	// @[src/main/scala/Coprocessor/VDecodeSimple.scala:98:7, :124:28, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}]
endmodule

module MDecodeSimple(	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:37:7]
  input  [31:0] io_in,	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:38:14]
  output        io_isMat,	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:38:14]
                io_isConfig,	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:38:14]
                io_xrs1,	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:38:14]
                io_xrs2,	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:38:14]
                io_xrd	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:38:14]
);

  wire [28:0] decoderOut0_invInputs = ~(io_in[31:3]);	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:38:14, src/main/scala/chisel3/util/pla.scala:78:21]
  wire [16:0] _decoderOut0_andMatrixOutputs_T =
    {io_in[0],
     io_in[1],
     io_in[2],
     decoderOut0_invInputs[0],
     io_in[4],
     io_in[5],
     io_in[6],
     decoderOut0_invInputs[8],
     decoderOut0_invInputs[9],
     io_in[13],
     decoderOut0_invInputs[11],
     decoderOut0_invInputs[23],
     decoderOut0_invInputs[24],
     decoderOut0_invInputs[25],
     decoderOut0_invInputs[26],
     decoderOut0_invInputs[27],
     decoderOut0_invInputs[28]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [20:0] _decoderOut0_andMatrixOutputs_T_1 =
    {io_in[0],
     io_in[1],
     io_in[2],
     decoderOut0_invInputs[0],
     io_in[4],
     io_in[5],
     io_in[6],
     decoderOut0_invInputs[9],
     decoderOut0_invInputs[10],
     io_in[14],
     decoderOut0_invInputs[17],
     decoderOut0_invInputs[18],
     decoderOut0_invInputs[19],
     decoderOut0_invInputs[20],
     decoderOut0_invInputs[21],
     decoderOut0_invInputs[22],
     decoderOut0_invInputs[24],
     decoderOut0_invInputs[25],
     decoderOut0_invInputs[26],
     decoderOut0_invInputs[27],
     decoderOut0_invInputs[28]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [17:0] _decoderOut0_andMatrixOutputs_T_2 =
    {io_in[0],
     io_in[1],
     io_in[2],
     decoderOut0_invInputs[0],
     io_in[4],
     io_in[5],
     io_in[6],
     decoderOut0_invInputs[8],
     decoderOut0_invInputs[9],
     decoderOut0_invInputs[10],
     decoderOut0_invInputs[11],
     decoderOut0_invInputs[22],
     io_in[26],
     decoderOut0_invInputs[24],
     decoderOut0_invInputs[25],
     decoderOut0_invInputs[26],
     decoderOut0_invInputs[27],
     decoderOut0_invInputs[28]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [20:0] _decoderOut0_andMatrixOutputs_T_3 =
    {io_in[0],
     io_in[1],
     io_in[2],
     decoderOut0_invInputs[0],
     io_in[4],
     io_in[5],
     io_in[6],
     decoderOut0_invInputs[9],
     io_in[14],
     decoderOut0_invInputs[17],
     decoderOut0_invInputs[18],
     decoderOut0_invInputs[19],
     decoderOut0_invInputs[20],
     decoderOut0_invInputs[21],
     decoderOut0_invInputs[22],
     io_in[26],
     decoderOut0_invInputs[24],
     decoderOut0_invInputs[25],
     decoderOut0_invInputs[26],
     decoderOut0_invInputs[27],
     decoderOut0_invInputs[28]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [20:0] _decoderOut0_andMatrixOutputs_T_4 =
    {io_in[0],
     io_in[1],
     io_in[2],
     decoderOut0_invInputs[0],
     io_in[4],
     io_in[5],
     io_in[6],
     decoderOut0_invInputs[10],
     io_in[14],
     decoderOut0_invInputs[17],
     decoderOut0_invInputs[18],
     decoderOut0_invInputs[19],
     decoderOut0_invInputs[20],
     decoderOut0_invInputs[21],
     decoderOut0_invInputs[22],
     io_in[26],
     decoderOut0_invInputs[24],
     decoderOut0_invInputs[25],
     decoderOut0_invInputs[26],
     decoderOut0_invInputs[27],
     decoderOut0_invInputs[28]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [17:0] _decoderOut0_andMatrixOutputs_T_5 =
    {io_in[0],
     io_in[1],
     io_in[2],
     decoderOut0_invInputs[0],
     io_in[4],
     io_in[5],
     io_in[6],
     decoderOut0_invInputs[8],
     decoderOut0_invInputs[9],
     decoderOut0_invInputs[10],
     decoderOut0_invInputs[11],
     decoderOut0_invInputs[22],
     decoderOut0_invInputs[23],
     io_in[27],
     decoderOut0_invInputs[25],
     decoderOut0_invInputs[26],
     decoderOut0_invInputs[27],
     decoderOut0_invInputs[28]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  assign io_isMat =
    |{&_decoderOut0_andMatrixOutputs_T,
      &_decoderOut0_andMatrixOutputs_T_1,
      &_decoderOut0_andMatrixOutputs_T_2,
      &_decoderOut0_andMatrixOutputs_T_3,
      &_decoderOut0_andMatrixOutputs_T_4,
      &_decoderOut0_andMatrixOutputs_T_5};	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:37:7, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign io_isConfig =
    |{&_decoderOut0_andMatrixOutputs_T_1,
      &_decoderOut0_andMatrixOutputs_T_3,
      &_decoderOut0_andMatrixOutputs_T_4};	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:37:7, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign io_xrs1 =
    |{&_decoderOut0_andMatrixOutputs_T,
      &_decoderOut0_andMatrixOutputs_T_1,
      &_decoderOut0_andMatrixOutputs_T_2,
      &_decoderOut0_andMatrixOutputs_T_3,
      &_decoderOut0_andMatrixOutputs_T_4,
      &_decoderOut0_andMatrixOutputs_T_5};	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:37:7, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign io_xrs2 =
    |{&_decoderOut0_andMatrixOutputs_T,
      &_decoderOut0_andMatrixOutputs_T_2,
      &_decoderOut0_andMatrixOutputs_T_5};	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:37:7, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign io_xrd =
    |{&_decoderOut0_andMatrixOutputs_T_1,
      &_decoderOut0_andMatrixOutputs_T_3,
      &_decoderOut0_andMatrixOutputs_T_4};	// @[src/main/scala/Coprocessor/MDecodeSimple.scala:37:7, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
endmodule

module First_Stage_Decoder(	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:6:7]
  input         io_issue_valid,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
  input  [31:0] io_issue_req_instr,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
  output        io_issue_ready,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
                io_issue_resp_accept,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
                io_issue_resp_writeback,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
  output [1:0]  io_issue_resp_register_read,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
  input         io_register_valid,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
  input  [63:0] io_register_rs_0,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
  input  [1:0]  io_register_rs_valid,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
  output [63:0] io_register_data_0,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
  output        io_isMat,	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
                io_isConfig	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:7:14]
);

  wire register_read_rs2;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:45:25, :47:23, :57:31]
  wire register_read_rs1;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:45:25, :46:23, :57:31]
  wire _MDecode_io_isMat;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:37:23]
  wire _MDecode_io_isConfig;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:37:23]
  wire _MDecode_io_xrs1;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:37:23]
  wire _MDecode_io_xrs2;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:37:23]
  wire _MDecode_io_xrd;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:37:23]
  wire _VDecode_io_isVec;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:36:23]
  wire _VDecode_io_isConfig;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:36:23]
  wire _VDecode_io_xrs1;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:36:23]
  wire _VDecode_io_xrs2;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:36:23]
  wire _VDecode_io_xrd;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:36:23]
  assign register_read_rs1 =
    _VDecode_io_isVec ? _VDecode_io_xrs1 : _MDecode_io_isMat & _MDecode_io_xrs1;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:36:23, :37:23, :45:25, :46:23, :57:31, :58:23, :70:27]
  assign register_read_rs2 =
    _VDecode_io_isVec ? _VDecode_io_xrs2 : _MDecode_io_isMat & _MDecode_io_xrs2;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:36:23, :37:23, :45:25, :47:23, :57:31, :59:23, :71:27]
  wire _GEN = _MDecode_io_isMat & io_issue_valid;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:37:23, :57:31, :60:22, :62:30, :66:30, :73:30]
  VDecodeSimple VDecode (	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:36:23]
    .io_in       (io_issue_req_instr),
    .io_isVec    (_VDecode_io_isVec),
    .io_isConfig (_VDecode_io_isConfig),
    .io_xrs1     (_VDecode_io_xrs1),
    .io_xrs2     (_VDecode_io_xrs2),
    .io_xrd      (_VDecode_io_xrd)
  );
  MDecodeSimple MDecode (	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:37:23]
    .io_in       (io_issue_req_instr),
    .io_isMat    (_MDecode_io_isMat),
    .io_isConfig (_MDecode_io_isConfig),
    .io_xrs1     (_MDecode_io_xrs1),
    .io_xrs2     (_MDecode_io_xrs2),
    .io_xrd      (_MDecode_io_xrd)
  );
  assign io_issue_ready =
    io_issue_valid & io_register_valid & (io_register_rs_valid[0] | ~register_read_rs1)
    & (io_register_rs_valid[1] | ~register_read_rs2);	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:6:7, :45:25, :46:23, :47:23, :57:31, :78:{36,40,44}, :79:{36,40,44}, :81:61]
  assign io_issue_resp_accept = (_VDecode_io_isVec | _MDecode_io_isMat) & io_issue_valid;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:6:7, :36:23, :37:23, :45:25, :48:22, :57:31, :60:22, :72:27]
  assign io_issue_resp_writeback =
    _VDecode_io_isVec ? io_issue_valid & _VDecode_io_xrd : _GEN & _MDecode_io_xrd;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:6:7, :36:23, :37:23, :45:25, :48:22, :50:30, :54:30, :57:31, :60:22, :62:30, :66:30, :73:30]
  assign io_issue_resp_register_read =
    _VDecode_io_isVec
      ? (io_issue_valid ? {register_read_rs2, register_read_rs1} : 2'h0)
      : _GEN ? {register_read_rs2, register_read_rs1} : 2'h0;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:6:7, :36:23, :45:25, :46:23, :47:23, :48:22, :51:{34,40}, :55:34, :57:31, :60:22, :62:30, :63:{34,40}, :66:30, :67:34, :73:30, :74:34]
  assign io_register_data_0 = io_register_rs_0;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:6:7]
  assign io_isMat = _MDecode_io_isMat;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:6:7, :37:23]
  assign io_isConfig = _VDecode_io_isConfig | _MDecode_io_isConfig;	// @[src/main/scala/Coprocessor/First_Stage_Decoder.scala:6:7, :36:23, :37:23, :86:45]
endmodule

module MCSR(	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
  input         clock,	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
                reset,	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
  input  [31:0] io_in,	// @[src/main/scala/Coprocessor/MCSR.scala:41:16]
  input         io_isConfig,	// @[src/main/scala/Coprocessor/MCSR.scala:41:16]
  input  [31:0] io_xrs1,	// @[src/main/scala/Coprocessor/MCSR.scala:41:16]
  output [31:0] io_xrd	// @[src/main/scala/Coprocessor/MCSR.scala:41:16]
);

  reg  [31:0] csr_0;	// @[src/main/scala/Coprocessor/MCSR.scala:55:22]
  wire [28:0] decoderOut_invInputs = ~(io_in[31:3]);	// @[src/main/scala/Coprocessor/MCSR.scala:41:16, src/main/scala/chisel3/util/pla.scala:78:21]
  wire [21:0] _decoderOut_andMatrixOutputs_T =
    {io_in[0],
     io_in[1],
     io_in[2],
     decoderOut_invInputs[0],
     io_in[4],
     io_in[5],
     io_in[6],
     decoderOut_invInputs[9],
     decoderOut_invInputs[10],
     io_in[14],
     decoderOut_invInputs[17],
     decoderOut_invInputs[18],
     decoderOut_invInputs[19],
     decoderOut_invInputs[20],
     decoderOut_invInputs[21],
     decoderOut_invInputs[22],
     decoderOut_invInputs[23],
     decoderOut_invInputs[24],
     decoderOut_invInputs[25],
     decoderOut_invInputs[26],
     decoderOut_invInputs[27],
     decoderOut_invInputs[28]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  always @(posedge clock) begin	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
    if (reset)	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
      csr_0 <= 32'h0;	// @[src/main/scala/Coprocessor/MCSR.scala:55:{22,30}]
    else if (io_isConfig & (&_decoderOut_andMatrixOutputs_T))	// @[src/main/scala/Coprocessor/MCSR.scala:55:22, :73:23, :74:43, :75:34, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
      csr_0 <= io_xrs1;	// @[src/main/scala/Coprocessor/MCSR.scala:55:22]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
    initial begin	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
        csr_0 = _RANDOM[/*Zero width*/ 1'b0];	// @[src/main/scala/Coprocessor/MCSR.scala:40:7, :55:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/Coprocessor/MCSR.scala:40:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_xrd =
    io_isConfig
      ? ((&_decoderOut_andMatrixOutputs_T)
           ? csr_0
           : (&{io_in[0],
                io_in[1],
                io_in[2],
                decoderOut_invInputs[0],
                io_in[4],
                io_in[5],
                io_in[6],
                io_in[12],
                decoderOut_invInputs[10],
                io_in[14],
                decoderOut_invInputs[17],
                decoderOut_invInputs[18],
                decoderOut_invInputs[19],
                decoderOut_invInputs[20],
                decoderOut_invInputs[21],
                decoderOut_invInputs[22],
                io_in[26],
                decoderOut_invInputs[24],
                decoderOut_invInputs[25],
                decoderOut_invInputs[26],
                decoderOut_invInputs[27],
                decoderOut_invInputs[28]})
             | (&{io_in[0],
                  io_in[1],
                  io_in[2],
                  decoderOut_invInputs[0],
                  io_in[4],
                  io_in[5],
                  io_in[6],
                  decoderOut_invInputs[9],
                  decoderOut_invInputs[10],
                  io_in[14],
                  decoderOut_invInputs[17],
                  decoderOut_invInputs[18],
                  decoderOut_invInputs[19],
                  decoderOut_invInputs[20],
                  decoderOut_invInputs[21],
                  decoderOut_invInputs[22],
                  io_in[26],
                  decoderOut_invInputs[24],
                  decoderOut_invInputs[25],
                  decoderOut_invInputs[26],
                  decoderOut_invInputs[27],
                  decoderOut_invInputs[28]})
             | (&{io_in[0],
                  io_in[1],
                  io_in[2],
                  decoderOut_invInputs[0],
                  io_in[4],
                  io_in[5],
                  io_in[6],
                  decoderOut_invInputs[9],
                  io_in[13],
                  io_in[14],
                  decoderOut_invInputs[17],
                  decoderOut_invInputs[18],
                  decoderOut_invInputs[19],
                  decoderOut_invInputs[20],
                  decoderOut_invInputs[21],
                  decoderOut_invInputs[22],
                  io_in[26],
                  decoderOut_invInputs[24],
                  decoderOut_invInputs[25],
                  decoderOut_invInputs[26],
                  decoderOut_invInputs[27],
                  decoderOut_invInputs[28]})
               ? (io_xrs1 < 32'h9 ? io_xrs1 : 32'h8)
               : 32'h0)
      : 32'h0;	// @[src/main/scala/Coprocessor/MCSR.scala:40:7, :55:{22,30}, :72:12, :73:23, :74:43, :76:20, :77:50, :78:{26,38}, :80:24, :83:24, :85:50, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}]
endmodule

module Corprocessor(	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
  input         clock,	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
                reset,	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
                io_issue_valid,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  input  [31:0] io_issue_req_instr,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  input  [63:0] io_issue_req_hartid,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  input  [2:0]  io_issue_req_id,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  input  [63:0] io_register_data_0,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  input         io_isConfig,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
                io_isMat,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  output        io_result_valid,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  output [63:0] io_result_hartid,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  output [2:0]  io_result_id,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  output [63:0] io_result_data,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  output [4:0]  io_result_rd,	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
  output        io_result_we	// @[src/main/scala/Coprocessor/Coprocessor.scala:7:14]
);

  wire [31:0] _MCSR_io_xrd;	// @[src/main/scala/Coprocessor/Coprocessor.scala:37:20]
  reg         result_valid;	// @[src/main/scala/Coprocessor/Coprocessor.scala:29:30]
  reg  [63:0] result_hartid;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23]
  reg  [2:0]  result_id;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23]
  reg  [63:0] result_data;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23]
  reg  [4:0]  result_rd;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23]
  reg         result_we;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23]
  wire        _MCSR_io_isConfig_T_1 = io_isConfig & io_isMat & io_issue_valid;	// @[src/main/scala/Coprocessor/Coprocessor.scala:39:41]
  always @(posedge clock) begin	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
    if (reset) begin	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
      result_valid <= 1'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:29:30]
      result_hartid <= 64'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:{23,36}]
      result_id <= 3'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :30:23]
      result_data <= 64'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:{23,36}]
      result_rd <= 5'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:{23,36}]
      result_we <= 1'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:29:30, :30:23]
    end
    else begin	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
      result_valid <= io_issue_valid;	// @[src/main/scala/Coprocessor/Coprocessor.scala:29:30]
      result_hartid <= io_issue_req_hartid;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23]
      result_id <= io_issue_req_id;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23]
      result_data <= {32'h0, _MCSR_io_xrd};	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23, :37:20, :48:17]
      result_rd <= io_issue_req_instr[11:7];	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23, :46:35]
      result_we <= _MCSR_io_isConfig_T_1;	// @[src/main/scala/Coprocessor/Coprocessor.scala:30:23, :39:41]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
    initial begin	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
        end	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
        result_valid = _RANDOM[3'h0][0];	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :29:30]
        result_hartid = {_RANDOM[3'h0][31:1], _RANDOM[3'h1], _RANDOM[3'h2][0]};	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :29:30, :30:23]
        result_id = _RANDOM[3'h2][3:1];	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :30:23]
        result_data = {_RANDOM[3'h2][31:4], _RANDOM[3'h3], _RANDOM[3'h4][3:0]};	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :30:23]
        result_rd = _RANDOM[3'h4][8:4];	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :30:23]
        result_we = _RANDOM[3'h4][9];	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :30:23]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MCSR MCSR (	// @[src/main/scala/Coprocessor/Coprocessor.scala:37:20]
    .clock       (clock),
    .reset       (reset),
    .io_in       (io_issue_req_instr),
    .io_isConfig (_MCSR_io_isConfig_T_1),	// @[src/main/scala/Coprocessor/Coprocessor.scala:39:41]
    .io_xrs1     (io_register_data_0[31:0]),	// @[src/main/scala/Coprocessor/Coprocessor.scala:40:16]
    .io_xrd      (_MCSR_io_xrd)
  );
  assign io_result_valid = result_valid;	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :29:30]
  assign io_result_hartid = result_valid ? result_hartid : 64'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :29:30, :30:{23,36}, :34:26]
  assign io_result_id = result_valid ? result_id : 3'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :29:30, :30:23, :34:26]
  assign io_result_data = result_valid ? result_data : 64'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :29:30, :30:{23,36}, :34:26]
  assign io_result_rd = result_valid ? result_rd : 5'h0;	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :29:30, :30:{23,36}, :34:26]
  assign io_result_we = result_valid & result_we;	// @[src/main/scala/Coprocessor/Coprocessor.scala:6:7, :29:30, :30:23, :34:26]
endmodule

module cvxif_example_coprocessor(	// @[src/main/scala/Coprocessor/Top.scala:6:7]
  input         clock,	// @[src/main/scala/Coprocessor/Top.scala:6:7]
                reset,	// @[src/main/scala/Coprocessor/Top.scala:6:7]
                io_req_compressed_valid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [15:0] io_req_compressed_req_instr,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [63:0] io_req_compressed_req_hartid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input         io_req_issue_valid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [31:0] io_req_issue_req_instr,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [63:0] io_req_issue_req_hartid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [2:0]  io_req_issue_req_id,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input         io_req_register_valid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [63:0] io_req_register_hartid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [2:0]  io_req_register_id,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [63:0] io_req_register_rs_0,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
                io_req_register_rs_1,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [1:0]  io_req_register_rs_valid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input         io_req_commit_valid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [63:0] io_req_commit_hartid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input  [2:0]  io_req_commit_id,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  input         io_req_commit_commit_kill,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
                io_req_result_ready,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output        io_resp_compressed_ready,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output [31:0] io_resp_compressed_resp_instr,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output        io_resp_compressed_resp_accept,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
                io_resp_issue_ready,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
                io_resp_issue_resp_accept,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
                io_resp_issue_resp_writeback,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output [1:0]  io_resp_issue_resp_register_read,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output        io_resp_register_ready,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
                io_resp_result_valid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output [63:0] io_resp_result_hartid,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output [2:0]  io_resp_result_id,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output [63:0] io_resp_result_data,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output [4:0]  io_resp_result_rd,	// @[src/main/scala/Coprocessor/Top.scala:7:14]
  output        io_resp_result_we	// @[src/main/scala/Coprocessor/Top.scala:7:14]
);

  wire        _decoder_io_issue_ready;	// @[src/main/scala/Coprocessor/Top.scala:20:23]
  wire        _decoder_io_issue_resp_accept;	// @[src/main/scala/Coprocessor/Top.scala:20:23]
  wire [63:0] _decoder_io_register_data_0;	// @[src/main/scala/Coprocessor/Top.scala:20:23]
  wire        _decoder_io_isMat;	// @[src/main/scala/Coprocessor/Top.scala:20:23]
  wire        _decoder_io_isConfig;	// @[src/main/scala/Coprocessor/Top.scala:20:23]
  First_Stage_Decoder decoder (	// @[src/main/scala/Coprocessor/Top.scala:20:23]
    .io_issue_valid              (io_req_issue_valid),
    .io_issue_req_instr          (io_req_issue_req_instr),
    .io_issue_ready              (_decoder_io_issue_ready),
    .io_issue_resp_accept        (_decoder_io_issue_resp_accept),
    .io_issue_resp_writeback     (io_resp_issue_resp_writeback),
    .io_issue_resp_register_read (io_resp_issue_resp_register_read),
    .io_register_valid           (io_req_register_valid),
    .io_register_rs_0            (io_req_register_rs_0),
    .io_register_rs_valid        (io_req_register_rs_valid),
    .io_register_data_0          (_decoder_io_register_data_0),
    .io_isMat                    (_decoder_io_isMat),
    .io_isConfig                 (_decoder_io_isConfig)
  );
  Corprocessor core (	// @[src/main/scala/Coprocessor/Top.scala:27:20]
    .clock               (clock),
    .reset               (reset),
    .io_issue_valid      (_decoder_io_issue_ready & _decoder_io_issue_resp_accept),	// @[src/main/scala/Coprocessor/Top.scala:20:23, :28:49]
    .io_issue_req_instr  (io_req_issue_req_instr),
    .io_issue_req_hartid (io_req_issue_req_hartid),
    .io_issue_req_id     (io_req_issue_req_id),
    .io_register_data_0  (_decoder_io_register_data_0),	// @[src/main/scala/Coprocessor/Top.scala:20:23]
    .io_isConfig         (_decoder_io_isConfig),	// @[src/main/scala/Coprocessor/Top.scala:20:23]
    .io_isMat            (_decoder_io_isMat),	// @[src/main/scala/Coprocessor/Top.scala:20:23]
    .io_result_valid     (io_resp_result_valid),
    .io_result_hartid    (io_resp_result_hartid),
    .io_result_id        (io_resp_result_id),
    .io_result_data      (io_resp_result_data),
    .io_result_rd        (io_resp_result_rd),
    .io_result_we        (io_resp_result_we)
  );
  assign io_resp_compressed_ready = 1'h1;	// @[src/main/scala/Coprocessor/Top.scala:6:7, :36:25]
  assign io_resp_compressed_resp_instr = 32'h0;	// @[src/main/scala/Coprocessor/Top.scala:6:7, :37:30]
  assign io_resp_compressed_resp_accept = 1'h0;	// @[src/main/scala/Coprocessor/Top.scala:6:7, :37:30]
  assign io_resp_issue_ready = _decoder_io_issue_ready;	// @[src/main/scala/Coprocessor/Top.scala:6:7, :20:23]
  assign io_resp_issue_resp_accept = _decoder_io_issue_resp_accept;	// @[src/main/scala/Coprocessor/Top.scala:6:7, :20:23]
  assign io_resp_register_ready = 1'h1;	// @[src/main/scala/Coprocessor/Top.scala:6:7, :36:25]
endmodule

